{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-service.fullname" . }}-secret
  labels:
    {{- include "ai-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end -}}
